name: Swift

on:
  pull_request:
  push:
    branches: [main]

jobs:
  format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew install swiftformat
      - run: swiftformat Sources Tests Package.swift --lint --reporter github-actions-log --cache ignore
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: swift build
      - run: swift test
